### PR TITLE
Expose the trace context from the worker

### PR DESCRIPTION
**Pull request by allenhumphreys**
As best I can tell, this update will simply allow typed/known access to values that already exist but aren't yet exposed.

Having access to these values is very helpful for tracing instrumentation.

References:
https://github.com/Azure/azure-functions-python-worker/blob/main/azure_functions_worker/bindings/context.py
https://github.com/Azure/azure-functions-python-worker/blob/698c524db03b70b13fb42d17e7b986ea8f744b6d/azure_functions_worker/bindings/tracecontext.py
https://github.com/Azure/azure-functions-python-worker/pull/545/files#diff-4b26101cf19d671ade506a5f9623a651bd389240b020b6176061abca184b2b6e

Screen Shot 2021-06-24 at 11 42 00 AM

### CODE REVIEW

**Review by Hazhzeng — APPROVED** [review]

**Comment by allenhumphreys** [comment]
@vrdmr  @AnatoliB Anything I can do to move this forward?

**Comment by allenhumphreys** [comment]
This effort seems to have been duplicated by @gavin-aguiar some 4 months later on #96 

If you don't accept PRs from the public, you should probably turn that off.

**Comment by stefanushinardi** [comment]
Hello @allenhumphreys, we apologize for the miss on our side. It wasn't our intention to not merge your PR.  Hazhzeng left the team and some of the context was missed during the transition.

**Comment by allenhumphreys** [comment]
@stefanushinardi thanks you for the apology and explanation 🙏🏼. Knowledge transfer can be super tricky! 

Glad to have these properties fully support either way!

**Pull request closed without merging**
