### PR TITLE
Add type hints to `HttpResponse`

### PR DESCRIPTION
**Pull request by michelole**
It seems `HttpResponse` is the only class in this file that does not contain type hints.

This generates errors when client code is checked using `mypy` in strict mode:
```
error: Call to untyped function "HttpResponse" in typed context
```

Add type hints following the docstring.

### CODE REVIEW

**Review by vrdmr — APPROVED** [review]

**Comment by vrdmr** [comment]
@tonybaloney - I think this change will need a corresponding change in `_http_asgi.py` to fix the type annotations for the headers in `to_func_response`.

```python
=================================== FAILURES ===================================
__________________________ TestCodeQuality.test_mypy ___________________________
Traceback (most recent call last):
  File "/home/runner/work/azure-functions-python-library/azure-functions-python-library/tests/test_code_quality.py", line 32, in test_mypy
    f'mypy validation failed:\n{output}') from None
AssertionError: mypy validation failed:
azure/functions/_http_asgi.py:73: error: Argument "headers" to "HttpResponse" has incompatible type "Union[Headers, Dict[Any, Any]]"; expected "Optional[Mapping[str, str]]"
Found 1 error in 1 file (checked 45 source files)

```

**Comment by michelole** [comment]
@vrdmr @gavin-aguiar Any updates here? Since the `mypy` error was fixed, could we remove the "Blocked" label?

**Comment by michelole** [comment]
@AnatoliB @anirudhgarg @gavin-aguiar Could you have a look on this PR as required reviewers?

Ps.: @vrdmr It seems tests are failing/cancelling across all builds and are not related to this PR only.

**Review by vrdmr — APPROVED** [review]
LGTM.

**Comment by vrdmr** [comment]
Thanks a lot, @michelole for the contribution, and apologies for the delay.

I'll fix the CI issues with our workflow caused due to a PR coming from a fork. Thanks again.

**Pull request merged**
