### PR TITLE
Add tests for QueueMessage

### PR DESCRIPTION
**Pull request by t-eckert**
I'm going to add some more tests. I just really like Python Azure Functions and want to make it better. Can we add a `dev` branch to the base repo for merging PRs?

### CODE REVIEW

**Comment by t-eckert** [comment]
@elprans, any thoughts?

**Comment by t-eckert** [comment]
Will do tonight.

**Comment by t-eckert** [comment]
@elprans, wrapped the tests in TestCase

**Comment by maiqbal11** [comment]
Hi @t-eckert, I've enabled CI for PRs to this repo's dev. You can update your PR to fix the test failures and we should be able to merge in. Thanks for your contribution!

**Comment by t-eckert** [comment]
@maiqbal11 Fixed the lines causing the failure :)

**Comment by maiqbal11** [comment]
@t-eckert, could you also rebase on `dev`? I updated the default base branch from `master` to `dev` in line with good practice. :)

**Comment by t-eckert** [comment]
@maiqbal11 I rebased. Worth noting, I am testing across different Python versions locally so I have virtual envs: `.venv-py36`, `.venv-py37` so I added a wildcard to the `.gitignore` to ignore anything beginning with `.venv`. I hope that is ok.

**Pull request merged**
