### PR TITLE
No temporary loop for ASGI middleware

### PR DESCRIPTION
**Pull request by tonybaloney**
Fixes https://github.com/Azure/azure-functions-python-library/issues/164 

get_event_loop() is deprecated in Python 3.10, but the replacement, get_running_loop() will raise a runtime error if there is no event loop, so `asyncio.run()` is a better solution, compatible with Python 3.7+.

### CODE REVIEW

**Comment by tonybaloney** [comment]
"compatible with Python 3.7+"

Python 3.6 is failing. Are we still supporting 3.6?

**Review by gavin-aguiar — APPROVED** [review]

**Comment by tonybaloney** [comment]
3.6 isn't supported anymore, I could add a shim for this PR to get the 3.6 test passing, but it would add extra software debt to the project for no reason.

**Comment by tonybaloney** [comment]
Suggest merging after #152

**Comment by tonybaloney** [comment]
@YunchuWang this is passing now, ready to merge

**Pull request merged**
