### PR TITLE
feat: Add MySql Binding Support V1

### PR DESCRIPTION
**Pull request by guptaheena**
Adding MySql Decorators V1 model

### CODE REVIEW

**Review by YunchuWang — APPROVED** [review]

**Comment by YunchuWang** [comment]
can you fix the pipelines errors?

**Comment by hallvictoria** [comment]
Can you also add decorators for mysql? You can add the file under `decorators/` and make changes to `decorators/function_app.py`. For example, see this PR: https://github.com/Azure/azure-functions-python-library/pull/234/files

Thanks for doing this!

**Review by gavin-aguiar — APPROVED** [review]

**Review by hallvictoria — APPROVED** [review]

**Pull request merged**
